path: .
jobs: 5

extensions:
  - php

exclude:
  - .cursor
  - .github
  - .idea
  - .vscode
  - .wordpress-org
  - assets
  - bin
  - dev-workspace-cache
  - dist
  - docs
  - languages
  - lib/vendor
  - node_modules
  - tests
  - vendor
