#!/usr/bin/env node

import { runDeploy } from '../deploy/engine.mjs';
import {
  preflight,
  gitConfig,
  githubAuth,
  branchSetup,
  mergeHotfixes,
  depDryRun,
  depReview,
  buildJs,
  checkQualityPhp,
  checkQualityLint,
  checkQualityCs,
  checkQualityLongpath,
  testUnit,
  testIntegration,
  translateAi,
  translateCommit,
  waitTranslator,
  translateDownload,
  translateCompile,
  changelogI18n,
  changelogReady,
  setVersion,
  commitRelease,
  buildPackage,
  teamTesting,
  createPr,
  mergeToMaster,
  mergeToDevelopment,
  githubRelease,
  postRelease,
} from '../deploy/steps/index.mjs';

runDeploy([
  preflight,
  gitConfig,
  githubAuth,
  branchSetup,
  mergeHotfixes,
  depDryRun,
  depReview,
  buildJs,
  checkQualityPhp,
  checkQualityLint,
  checkQualityCs,
  checkQualityLongpath,
  testUnit,
  testIntegration,
  translateAi,
  translateCommit,
  waitTranslator,
  translateDownload,
  translateCompile,
  changelogI18n,
  changelogReady,
  setVersion,
  commitRelease,
  buildPackage,
  teamTesting,
  createPr,
  mergeToMaster,
  mergeToDevelopment,
  githubRelease,
  postRelease,
]);
