#!/usr/bin/env bash

# Make sure we are inside dev-workspace subdirectory. If not, enter it.
if [[ ! "$PWD" =~ dev-workspace$ ]]; then
    cd dev-workspace
fi

CACHE_NAME_LAST_UPDATE="cache/.last_image_update_check"
ONE_DAY_IN_SECONDS=86400
UPDATE_CHECK_INTERVAL=$ONE_DAY_IN_SECONDS

# Create empty cache files if not exists.
[[ -d cache ]] || mkdir -p cache
[[ -d cache/.npm/_cacache ]] || mkdir -p cache/.npm/_cacache
[[ -d cache/.npm/_logs ]] || mkdir -p cache/.npm/_logs
[[ -d cache/.composer/cache ]] || mkdir -p cache/.composer/cache
[[ -d cache/.oh-my-zsh/log ]] || mkdir -p cache/.oh-my-zsh/log
[[ -f cache/.zsh_history ]] || touch cache/.zsh_history
[[ -f cache/.bash_history ]] || touch cache/.bash_history
[[ -f cache/.composer/auth.json ]] || echo '{}' > cache/.composer/auth.json

run_terminal_service() {
    docker compose -f docker/compose.yaml run --rm terminal "$@"
}

save_past_date_to_cache() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS uses BSD date
        date -v -7d +%s > $CACHE_NAME_LAST_UPDATE
    else
        # Ubuntu uses GNU date
        date --date="7 days ago" +%s > $CACHE_NAME_LAST_UPDATE
    fi
}

get_last_update_from_cache() {
    init_cache_if_not_exists

    echo $(cat $CACHE_NAME_LAST_UPDATE)
}

init_cache_if_not_exists() {
    if [[ ! -f $CACHE_NAME_LAST_UPDATE ]]; then
        save_past_date_to_cache
    fi
}

should_update() {
    LAST_UPDATE=$(get_last_update_from_cache)
    TODAY=$(date +%s)

    if [[ $(($TODAY - $LAST_UPDATE)) -gt UPDATE_CHECK_INTERVAL ]]; then
        echo 1
    else
        echo 0
    fi
}

# If should_update returns 1, it means we should update the image.
if [[ $(should_update) -eq 1 ]]; then
    ./update
fi

run_terminal_service "$@"
