name: VIP Scans and other code checks
on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - '*'

  workflow_call:

  workflow_dispatch:
    inputs:
      tmate_enabled:
        type: boolean
        description: 'Enable "tmate" for debugging'
        required: false
        default: false
jobs:
  check:
    name: Check the code
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session for Debugging, if inputs.tmate_enabled is true
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.tmate_enabled }}
        timeout-minutes: 10
        with:
          detached: true

      - name: Show inspection of dev-workspace image
        run: |
          docker pull publishpress/dev-workspace-terminal:future-pro && \
            docker image inspect publishpress/dev-workspace-terminal:future-pro

      - name: Show version of tools
        run: |
          echo "PHP Version: $(php -v)"
          echo "Composer Version: $(composer --version)"
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"
          echo "Yarn Version: $(yarn -v)"

      - name: Checkout code
        uses: actions/checkout@master

      - name: Prepare composer
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer validate && composer install

      - name: Run code checks inside dev-workspace
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer check
