name: Unit and Integration Tests
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
      - 'release-*'

  pull_request:
    branches:
      - '*'

  workflow_call:

  workflow_dispatch:
    inputs:
      tmate_enabled:
        type: boolean
        description: 'Enable "tmate" for debugging'
        required: false
        default: false
jobs:
  check:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session for Debugging, if inputs.tmate_enabled is true
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.tmate_enabled }}
        timeout-minutes: 10
        with:
          detached: true

      - name: Checkout code
        uses: actions/checkout@master

      - name: Verify Docker installation
        run: docker --version

      - name: Create .env file
        run: |
          cp $GITHUB_WORKSPACE/.env.example $GITHUB_WORKSPACE/.env

      - name: Prepare composer
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer validate
          $GITHUB_WORKSPACE/dev-workspace/run composer install

      - name: Start services
        run: |
          composer test:up

      - name: Fix permissions
        run: |
          container_id=$(docker compose -f $GITHUB_WORKSPACE/dev-workspace/docker/compose.yaml ps -q wp_test)
          docker exec $container_id chmod -R 777 /var/www/html/wp-content

      - name: Run Unit Tests
        run: |
          composer test Unit

      - name: Run Integration Tests
        run: |
          composer test Integration


