name: Unit and Integration Tests in the Pro plugin
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
      - 'release-*'

  pull_request:
    branches:
      - '*'

  workflow_call:

  workflow_dispatch:
    inputs:
      tmate_enabled:
        type: boolean
        description: 'Enable "tmate" for debugging'
        required: false
        default: false
jobs:
  check:
    name: Test the code in the Pro plugin
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session for Debugging, if inputs.tmate_enabled is true
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 10
        with:
          detached: true

      - name: Checkout pro plugin and update the branch in the composer.json file
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/publishpress/publishpress-future-pro.git .
          # Check if the branch exists in the repository
          if ! git ls-remote --heads origin ${{ github.ref_name }} | grep -q ${{ github.ref_name }}; then
            echo "Branch ${{ github.ref_name }} does not exist in the pro repository. Using develop branch instead."
            git checkout develop
          else
            git checkout ${{ github.ref_name }}
          fi
          # Change the branch in the composer.json
          php -r '
          $composerFile = "lib/composer.json";
          $ref = getenv("GITHUB_HEAD_REF");
          $data = json_decode(file_get_contents($composerFile), true);
          $data["require"]["publishpress/publishpress-future"] = "dev-" . $ref;
          file_put_contents($composerFile, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
          '
      - name: Show the changes in the composer.json file
        run: |
          git diff lib/composer.json

      - name: Store the Github credentials in the auth.json file
        run: |
          mkdir -p $GITHUB_WORKSPACE/dev-workspace/.cache/.composer
          php -r '
          $authFile = getenv("GITHUB_WORKSPACE") . "/dev-workspace/.cache/.composer/auth.json";
          $authData = ["github-oauth" => ["github.com" => "${{ secrets.GH_TOKEN }}"]];
          file_put_contents($authFile, json_encode($authData, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
          '

      - name: Verify Docker installation
        run: docker --version

      - name: Create .env file
        run: |
          cp $GITHUB_WORKSPACE/.env.example $GITHUB_WORKSPACE/.env

      - name: Prepare composer
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer validate
          $GITHUB_WORKSPACE/dev-workspace/run composer update

      - name: Start services
        run: |
          composer test:up

      - name: Fix permissions
        run: |
          container_id=$(docker compose -f $GITHUB_WORKSPACE/dev-workspace/docker/compose.yaml ps -q wp_tests)
          docker exec $container_id chmod -R 777 /var/www/html/wp-content

      - name: Run Unit Tests
        run: |
          composer test Unit

      - name: Run Integration Tests
        run: |
          composer test Integration


