name: VIP Scans and other code checks
permissions:
  contents: read
on:
  push:
    branches:
      - 'main'
      - 'hotfix/github-workflow'

  pull_request:
    branches:
      - '*'

  workflow_call:

env:
  DEV_SCRIPTS_DIR: ${{ github.workspace }}/vendor/publishpress/dev-workspace/scripts

jobs:
  check:
    name: Check the code
    runs-on: [self-hosted, precheck]
    steps:
      - name: Checkout code
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Create .env file
        run: |
          cp $GITHUB_WORKSPACE/.env.example $GITHUB_WORKSPACE/.env

      - name: Create .env file
        run: |
          cp $GITHUB_WORKSPACE/.env.example $GITHUB_WORKSPACE/.env

      - name: Validate the composer.json file
        run: composer validate

      - name: Install the dependencies
        run: composer install

      - name: Show the version of the tools inside the dev-workspace
        run: composer info:version

      - name: Add dev-workspace scripts to PATH
        run: echo "$DEV_SCRIPTS_DIR" >> "$GITHUB_PATH"

      - name: Run PHP check
        run: |
          composer check:php

      - name: Run Lint check
        run: |
          composer check:lint

      - name: Run PHPCS check
        run: |
          composer check:cs
