name: Deploy plugin to WordPress.org
on:
  release:
    types: [ released ]

  workflow_dispatch:

jobs:
  code-check:
    name: Check the code
    uses: ./.github/workflows/code-check.yml
    secrets: inherit

  deploy-wp-org:
    name: Deploy the new tag
    needs: [code-check]
    runs-on: release,self-hosted
    steps:
      - name: Checkout code
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Create root .env from template
        run: |
          cp $GITHUB_WORKSPACE/.env.example $GITHUB_WORKSPACE/.env

      - name: Validate composer.json
        run: composer validate

      - name: Install Composer dependencies
        run: composer install

      - name: Show dev-workspace tool versions
        run: composer info:version

      - name: Add dev-workspace scripts to PATH
        run: echo "$DEV_SCRIPTS_DIR" >> "$GITHUB_PATH"

      - name: Build the plugin package
        run: composer build

      - name: Get the plugin version number
        id: get-version
        run: |
          PLUGIN_SLUG=$(jq -r '.extra["plugin-slug"]' composer.json)
          PLUGIN_FOLDER=$(jq -r '.extra["plugin-folder"]' composer.json)
          PLUGIN_NAME=$(jq -r '.extra["plugin-name"]' composer.json)
          PLUGIN_VERSION=$($GITHUB_WORKSPACE/vendor/publishpress/dev-workspace/scripts/plugin-version.sh)
          echo "plugin_slug=${PLUGIN_SLUG}" >> "$GITHUB_OUTPUT"
          echo "plugin_folder=${PLUGIN_FOLDER}" >> "$GITHUB_OUTPUT"
          echo "plugin_name=${PLUGIN_NAME}" >> "$GITHUB_OUTPUT"
          echo "plugin_version=${PLUGIN_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Upload release asset
        # softprops/action-gh-release@v3.0.0
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
        with:
          files: ${{ github.workspace }}/dist/${{ steps.get-version.outputs.plugin_name }}-${{ steps.get-version.outputs.plugin_version }}.zip

      - name: WordPress.org plugin deploy
        # 10up/action-wordpress-plugin-deploy@v2.3.0
        uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ steps.get-version.outputs.plugin_slug }}
          BUILD_DIR: ${{ github.workspace }}/dist/${{ steps.get-version.outputs.plugin_folder }}
