name: Deploy assets/readme to WordPress.org
permissions:
  contents: read
on:
  push:
    branches:
      - 'master'

jobs:
  deploy-to-trunk:
    name: Deploy assets/readme to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: WordPress.org plugin asset/readme update
        uses: publishpress/github-workflows/.github/workflows/deploy-free-assets.yml@v1.0.0
