name: Deploy plugin to WordPress.org
on:
  release:
    types: [ released ]

jobs:
  code-check:
    name: Check the code
    uses: ./.github/workflows/code-standards.yml
    secrets: inherit

  run-unit-tests:
    name: Run unit tests
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  deploy-wp-org:
    permissions:
      contents: write
    uses: publishpress/github-workflows/.github/workflows/deploy-free.yml@v3
    needs: [code-check, run-unit-tests]
    secrets: inherit
