name: Deploy assets/readme to WordPress.org
permissions:
  contents: read
on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  deploy-to-trunk:
    name: Deploy assets/readme to trunk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: WordPress.org plugin asset/readme update
      # 10up/action-wordpress-plugin-asset-update@v2.2.0
        uses: 10up/action-wordpress-plugin-asset-update@2480306f6f693672726d08b5917ea114cb2825f7
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: post-expirator
          IGNORE_OTHER_FILES: true
