name: PHP v5 Support

on:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: php5-support-${{ github.ref }}-1
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  php5_check:
    uses: publishpress/github-workfows/.github/workflows/php5-support.yml@main
