name: PHP 7.2 Support

on:
  branch:
    branches:
      - 'main'
      - 'develop'
      - 'release-*'

  pull_request:
    branches:
      - 'main'
      - 'develop'

concurrency:
  group: php7.2-support-${{ github.ref }}-1
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  php72_check:
    uses: publishpress/github-workfows/.github/workflows/php7.2-support.yml@main
